import type { Metadata } from "next";
import "./globals.css";
import "cal-sans";
import {Providers} from "./Provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>
        {children}
        </Providers>
        </body>
    </html>
  );
}
